# Generated by Django 5.2.7 on 2025-10-02 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol_name', models.CharField(help_text='Role name (e.g., Administrator, User)', max_length=50, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Role creation date and time')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
                'ordering': ['rol_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.BigAutoField(help_text='Unique user ID', primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Unique username (3-20 alphanumeric characters)', max_length=150, unique=True)),
                ('email', models.EmailField(help_text="User's unique email address", max_length=255, unique=True)),
                ('password', models.CharField(help_text="User's hashed password", max_length=255)),
                ('user_state', models.BooleanField(default=True, help_text='User state (True=Active, False=Inactive)')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='User registration date and time')),
                ('rol', models.ForeignKey(help_text='Role assigned to user', on_delete=django.db.models.deletion.CASCADE, to='users.rol')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['username'], name='users_usernam_baeb4b_idx'), models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['user_state'], name='users_user_st_db8efc_idx')],
            },
        ),
    ]
